### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pprint 

### ISSUE THREAD

**Issue by mahdi-cll** [lethean-io/lethean-vpn#128]
```
$ pip3 install -r requirements.txt
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting syslogmp
  Downloading syslogmp-0.4-py3-none-any.whl (7.9 kB)
Collecting ed25519
  Downloading ed25519-1.5.tar.gz (868 kB)
     |████████████████████████████████| 868 kB 88 kB/s 
ERROR: Could not find a version that satisfies the requirement pprint (from -r requirements.txt (line 3)) (from versions: none)
ERROR: No matching distribution found for pprint (from -r requirements.txt (line 3))
```
I used `develop` branch

**Comment by mahdi-cll** [comment]
I tried this https://github.com/nithronium/lethean-vpn/commit/5db2d89a26b8613ea3663a095028c8ff7f6a07ab

**Comment by limosek** [comment]
Hi,

can you send more details about your OS, Pip and Python version? 
pprint is standard package which should be available.

**Comment by snider** [comment]
@mahdi-cll 
![image](https://user-images.githubusercontent.com/631881/118271133-cf4f6080-b4b8-11eb-8593-4154456f4315.png)

pprint was added to python, the fix is to remove it. 

Our gitlab is now pushing updates github master, so if you subscribe here you will only see improvements you can use and not dev work :)

This issue is fixed in GitHub Master, let us know if it pops back up :)
